services:

  # ======================================================
  # PostgreSQL
  # ======================================================
  fitness-user-db:
    image: postgres:16-alpine
    container_name: fitness-userdb-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: fitness_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./UserService/initScripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fitness-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======================================================
  # MongoDB
  # ======================================================
  fitness-activity-db:
    image: mongo:8.2
    container_name: fitness-activitydb-mongo
    restart: unless-stopped
    ports:
    - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: krishna
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: activitydb
    volumes:
    - mongodb_data:/data/db
    - ./ActivityService/initScripts/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
    - fitness-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======================================================
  # Apache Kafka (KRaft Mode)
  # ======================================================
#  fitness-kafka:
#    image: apache/kafka:4.3.0
#    container_name: fitness-kafka
#    restart: unless-stopped
#
#    ports:
#      - "9092:9092"
#
#    environment:
#      KAFKA_NODE_ID: 1
#
#      KAFKA_PROCESS_ROLES: broker,controller
#
#      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@fitness-kafka:9093
#
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#
#    volumes:
#      - kafka_data:/var/lib/kafka/data
#
#    networks:
#      - fitness-net
#
#    healthcheck:
#      test:
#        [
#          "CMD",
#          "/opt/kafka/bin/kafka-topics.sh",
#          "--bootstrap-server",
#          "localhost:9092",
#          "--list"
#        ]
#      interval: 15s
#      timeout: 10s
#      retries: 5

volumes:
  postgres_data:
  mongodb_data:
#  kafka_data:

networks:
  fitness-net:
    driver: bridge